Sprint2/step2
woofmgn/react-burger pull request #4
Opened 2023-02-20 15:33 UTC by woofmgn

В компоненте BurgerIngredients оставлен закомментированный код, для себя. В дальнейшем перепишу компонент, добавлю возможность перелистывать список ингредиентов по нажатию на табы.

2023-02-20 16:45 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную работу по добавления редакса и DnD в ваш проект, использовали модель файловой структуры с разделением на представление и хранилище, подготовили основу для работы с табами, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует вынести **базовый** адрес сервера `https://norma.nomoreparties.space/api` сервера в отдельную константу, т.к. это часть адреса не будет изменяться от запроса к запросу;
- Следует отключать счётчик на ингредиентах, когда его значение равно нулю, согласно дизайну (см. https://disk.yandex.ru/i/qfoAqjmeLi7fpw);
- Не следует вызывать API создания заказа, если в конструктор не были добавлена минимум булка, чтобы не нагружать сервер;
- В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам;
- Не следует разделять единый объект ингредиента в отдельные его составляющие, если используются все или большая часть его ключей, передавайте его в компонент или в стор полностью, а внутри можно будет разделить;
- Ключ следует генерировать **в момент добавления ингредиента в стор** (`ADD_INGREDIENTS`), т.к. в данном случае при каждом рендере будет генерироваться новый ключ - он будет уникальным, но не будет **постоянным** для данного элемента, а следовательно - будут лишние ререндеры.

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-20 16:45 UTC, randomroot commented on src/utils/constants.js
> +  urlGetData: "https://norma.nomoreparties.space/api/ingredients",
🔴 **Нужно исправить:**

Следует вынести базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в отдельную константу, т.к. это часть адреса не будет изменяться от запроса к запросу

2023-02-20 16:45 UTC, randomroot commented on src/Components/Ingredient/Ingredient.jsx
> +      ref={(node) => drag(drop(node))}
🟡 **Можно улучшить:**

Имеет смысл использовать хук `useRef` в данном случае и полученную константу хука передать в функцию `drag(drop(...))`

2023-02-20 16:45 UTC, randomroot commented on src/Components/Card/Card.jsx
> +        style={{ textAlign: "center" }}
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-02-20 16:45 UTC, randomroot commented on src/Components/Card/Card.jsx
> +      className={classNames(styles.item, {}, [])}
🟡 **Можно улучшить:**

В данном случае `classNames` не требуется, т.к. указан только один класс

2023-02-20 16:45 UTC, randomroot commented on src/Components/Card/Card.jsx
> +    return inCart.length;
🟡 **Можно улучшить:**

Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2023-02-20 16:45 UTC, randomroot commented on src/utils/prop-types.js
> +  onOpen: PropTypes.func,
🟡 **Можно улучшить:** 

Функция `onOpen` не относится именно к ингредиенту, поэтому имеет смысл вынести её, или создать отдельный тип на базе текущего

2023-02-20 16:45 UTC, randomroot commented on src/services/reducers/orderReducer.js
> +  order: {},
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2023-02-20 16:45 UTC, randomroot commented on src/services/reducers/orderReducer.js
> +      return action;
🟡 **Можно улучшить:**

В данном случае имеет смысл возвращать начальное состояние стора в `initialState`

2023-02-20 16:45 UTC, randomroot commented on src/services/reducers/detailsReduser.js
> +  carbohydrates: "",
🔴 **Нужно исправить:**

Не следует разделять единый объект ингредиента в отдельные его составляющие, храните в сторе объект целиком, а в рамках компонента извлекайте необходимые свойства

2023-02-20 16:45 UTC, randomroot commented on src/services/reducers/detailsReduser.js
> +    default: {
🟡 **Можно улучшить:**

Имеет смысл добавить экшн сбора стора при закрытии модального окна

2023-02-20 16:45 UTC, randomroot commented on src/services/reducers/constructorReducer.js
> +};
🟡 **Можно улучшить:**

Имеет смысл вынести булочку в отдельный ключ, чтобы удобно управлять её состоянием не проходя по массиву ингредиентов

2023-02-20 16:45 UTC, randomroot commented on src/services/actions/details.js
> +  name: "",
🟡 **Можно улучшить:**

Имеет смысл просто в сторе возвращать начальное состояние, не дублируя его в экшн креаторе

2023-02-20 16:45 UTC, randomroot commented on src/Components/BurgerIngredients/BurgerIngredients.jsx
> +                    key={item._id}
🔴 **Нужно исправить:**

Не следует разделять ингредиент на несколько пропсов, объект следует передавать внутрь целиком, а затем внутри извлекать нужные ключи

**Аналогично ниже**

2023-02-20 16:45 UTC, randomroot commented on src/Components/BurgerConstructor/BurgerConstructor.jsx
> +                    key={uuid()}
🔴 **Нужно исправить:**

Ключ следует генерировать **в момент добавления ингредиента в стор** (`ADD_INGREDIENTS`), т.к. в данном случае при каждом рендере будет генерироваться новый ключ - он будет уникальным, но не будет **постоянным** для данного элемента, а следовательно - будут лишние ререндеры.

2023-02-20 18:01 UTC, woofmgn commented on src/services/reducers/detailsReduser.js
> +    default: {
Речь о сбросе стора, правило понял? :)

2023-02-20 18:26 UTC, randomroot commented on src/services/reducers/detailsReduser.js
> +    default: {
Всё верно, опечатка)

2023-02-21 12:53 UTC, woofmgn commented on src/Components/Card/Card.jsx
> +    return inCart.length;
Большо спасибо, это отличная идея. Подумаю над тем, как это корректно реализовать!

2023-02-21 15:06 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-21 15:06 UTC, randomroot commented on src/Components/BurgerIngredients/BurgerIngredients.jsx
>            <ul className={styles.grid}>
🟡 **Можно улучшить:**

Обратите внимание, что код категорий дублируется, поэтому можно его вынести в отдельный компонент :)

2023-02-21 15:34 UTC, merged